[workspace]
members = ["service", "program-keccak-inclusion", "common", "blob-tool", "runner-keccak-inclusion", "sdk"]
default-members = ["service"]
resolver = "2"

[workspace.dependencies]
celestia-types = {git="https://github.com/eigerco/lumina.git"}
celestia-rpc = {git="https://github.com/eigerco/lumina.git"}
nmt-rs = "0.2"
sp1-zkvm = {version="4.0", features=["verify"]}
sp1-sdk = {version="4.0"}
serde = { version = "1.0", default-features = false, features = ["derive"] }
sha3 = "0.10"
tendermint-proto = "0.40"
tendermint = "0.40"
bincode = "1.3"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
hex = "0.4"
serde_json = "1.0"
thiserror = "2.0"
sled = "0.34"
prost = "0.12.6"
tonic = { version = "0.11.0", default-features = false, features=["codegen"]}
tonic-build = { version = "0.11.0", default-features = false }
env_logger = "0.11"
log = "0.4"
base64 = "0.22"
jsonrpsee = "0.24"
alloy = { version = "0.9", default-features = false }

[patch.crates-io]
sha3-v0-10-8 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha3", branch = "patch-sha3-v0.10.8" }
sha2-v0-9-9 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", tag = "patch-sha2-0.9.9-sp1-4.0.0" }
sha2-v0-10-6 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", tag = "patch-sha2-0.10.6-sp1-4.0.0" }
sha2-v0-10-8 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", tag = "patch-sha2-0.10.8-sp1-4.0.0" }
tiny-keccak = { git = "https://github.com/sp1-patches/tiny-keccak", tag = "patch-2.0.2-sp1-4.0.0" }
curve25519-dalek = { git = "https://github.com/sp1-patches/curve25519-dalek", tag = "patch-4.1.3-sp1-4.0.0" }
curve25519-dalek-ng = { git = "https://github.com/sp1-patches/curve25519-dalek-ng", tag = "patch-4.1.1-sp1-4.0.0" }
